/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GraphD;
import controller.GraphND;
import javax.swing.JOptionPane;
import model.Graph;

/**
 *
 * @author Tom
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Index() {
        initComponents();
      
        setSize(900, 592);
       
        setResizable(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TypeGraph = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        directedOp = new javax.swing.JRadioButton();
        noDirectedOp = new javax.swing.JRadioButton();
        forwardButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(900, 529));
        setPreferredSize(new java.awt.Dimension(900, 592));

        jPanel1.setBackground(new java.awt.Color(42, 54, 59));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("GeosansLight", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 206, 171));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(org.openide.util.NbBundle.getMessage(Index.class, "Index.jLabel1.text")); // NOI18N

        TypeGraph.add(directedOp);
        directedOp.setFont(new java.awt.Font("GeosansLight", 1, 18)); // NOI18N
        directedOp.setForeground(new java.awt.Color(254, 206, 174));
        directedOp.setText(org.openide.util.NbBundle.getMessage(Index.class, "Index.directedOp.text")); // NOI18N
        directedOp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        directedOp.setFocusPainted(false);
        directedOp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oval.png"))); // NOI18N
        directedOp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png"))); // NOI18N
        directedOp.setRequestFocusEnabled(false);
        directedOp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-checkmark-24.png"))); // NOI18N
        directedOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directedOpActionPerformed(evt);
            }
        });

        TypeGraph.add(noDirectedOp);
        noDirectedOp.setFont(new java.awt.Font("GeosansLight", 1, 18)); // NOI18N
        noDirectedOp.setForeground(new java.awt.Color(254, 206, 174));
        noDirectedOp.setText(org.openide.util.NbBundle.getMessage(Index.class, "Index.noDirectedOp.text")); // NOI18N
        noDirectedOp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noDirectedOp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oval.png"))); // NOI18N
        noDirectedOp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png"))); // NOI18N
        noDirectedOp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-checkmark-24.png"))); // NOI18N
        noDirectedOp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noDirectedOpMouseClicked(evt);
            }
        });
        noDirectedOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noDirectedOpActionPerformed(evt);
            }
        });

        forwardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-right-100.png"))); // NOI18N
        forwardButton.setText(org.openide.util.NbBundle.getMessage(Index.class, "Index.forwardButton.text")); // NOI18N
        forwardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forwardButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-right-100disabled2.png"))); // NOI18N
        forwardButton.setEnabled(false);
        forwardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forwardButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(directedOp)
                        .addGap(177, 177, 177)
                        .addComponent(noDirectedOp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(forwardButton)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noDirectedOp)
                    .addComponent(directedOp))
                .addGap(18, 18, 18)
                .addComponent(forwardButton)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noDirectedOpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noDirectedOpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_noDirectedOpMouseClicked

    private void directedOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directedOpActionPerformed
        forwardButton.setEnabled(true);
    }//GEN-LAST:event_directedOpActionPerformed

    private void noDirectedOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noDirectedOpActionPerformed
        forwardButton.setEnabled(true);
        
    }//GEN-LAST:event_noDirectedOpActionPerformed

    private void forwardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forwardButtonMouseClicked
      if(forwardButton.isEnabled()){
        if(directedOp.isSelected()){
           System.out.println("Dirigido");
           GraphD graph_d = new GraphD();
            graph_d.GraphD();
           Home_D home_ = new Home_D(graph_d);
           home_.setVisible(true);
           setVisible(false);
           init_message();
           
        }else{
            GraphND graph_nd = new GraphND();
            graph_nd.GraphND();
            Home_ND home_ = new Home_ND(graph_nd);
            home_.setVisible(true);
            setVisible(false);
            System.out.println("No Dirigido");
       }
      }
    }//GEN-LAST:event_forwardButtonMouseClicked
    public void init_message(){
        JOptionPane.showMessageDialog(this, "Para ingresar nodos: Click en el panel");
        JOptionPane.showMessageDialog(this, "Para borrar nodo: Click derecho sobre el nodo");
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.ButtonGroup TypeGraph;
    private javax.swing.JRadioButton directedOp;
    private javax.swing.JLabel forwardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton noDirectedOp;
    // End of variables declaration//GEN-END:variables
}
